### ISSUE TITLE
Issue when parsing maps

### ISSUE THREAD

**Issue by jiaaluo** [Crabo-7498/btdb2-exp-grinder#8]
Playing on the left side
Traceback (most recent call last):
  File "main.py", line 92, in <module>
    for pos in p.get_positions(map, 'right' if is_right_side else 'left'):
  File "position_parser.py", line 19, in get_positions
    for pos in self.data[map][side]:
KeyError: None

Process finished with exit code 1

I am on 1920x1080 not entirely sure why it would be doing this

**Comment by vincent-qc** [comment]
Hi @jiaaluo,

The issue is caused when the bot cannot figure out which map you are playing on.
A few issues that may cause this are:
- You are not playing on windowed mode
- Your taskbar needs to be at the bottom
- The value `con_value` is too high in `util/map_finder.py` (lowering should fix this)

If you need any more help, feel free to contact me on Discord.
